name: CI/CD

on:
  push:
    branches: [prod]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t <dockerContainer> .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Delivery
        run: docker push <dockerContainer>
        